# Generated by Django 3.2.8 on 2021-11-27 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_project_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='writer',
        ),
    ]
